apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
  namespace: demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../../charts/backend
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: backend-values
    valuesKey: values.yaml